sms:
  niazpardazandeh:
    user-name: "t.09105501184"
    password: "jyp$200"
    from-number: "10009611"
    falsh: "false"
    send-delay: "0"
    login-verify-text: |
      فروشگاه‌اینترنتی بهتا‌تهویه‌قشم
      ورود به فروشگاه
      رمزعبور: %s
    transaction-code-text: |
      فروشگاه‌اینترنتی بهتا‌تهویه‌قشم
      کاربر گرامی: %s
      سفارش شما با موفقیت ثبت‌گردید. 
      کد‌پیگیری‌سفارش: %s
      فروشگاه اینترنتی بهتا تهویه قشم.
    ticket-text: |
      کاربر گرامی
      سلام، تیکت شما با موفقیت ثبت گردید و بزودی توسط کارشناسان ما پاسخ داده ‌خواهد شد.
      فروشگاه‌اینترنتی بهتا‌تهویه‌قشم.
      شناسه پیگیری: %s
    ticket-reply-text: |
      کاربر گرامی
      سلام، تیکت شماره %s پاسخ داده شد.
      فروشگاه‌اینترنتی بهتا‌تهویه‌قشم.
    provider-new-bill: |
      تامین‌کننده گرامی: %s
      فاکتور جدید با کدپیگیری %s در تاریخ %s ثبت گردید. لطفا بررسی بفرمایید.
      فروشگاه‌اینترنتی بهتا‌تهویه‌قشم.