spring:

  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
            lob.non_contextual_creation: true
    show-sql: false
    open-in-view: false
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/test_data_base
      username: postgres
      password: 1234567890
      initialization-mode: always

  session:
    store-type: redis
  profiles:
    include:
      - api
      - uploader
      - android
      - debug
      - bank
      - sms
  servlet:
    multipart:
      max-request-size: 15MB
      max-file-size: 15MB


server:
  port: 7411
  servlet:
    context-path: /
    session:
      cookie:
        name: behta-tahvie-server

logging:
  file:
    max-size: 15MB